# Generated by Django 5.2.1 on 2025-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
