# Generated by Django 5.2.1 on 2025-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_submission_teacher_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
