# Generated by Django 5.2.1 on 2025-08-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='openai_score',
            field=models.FloatField(blank=True, help_text='Score given by OpenAI model.', null=True),
        ),
    ]
