# Generated by Django 5.2.3 on 2025-10-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_submission_openai_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
