# Generated by Django 5.2.1 on 2025-07-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
