# Generated by Django 5.2.1 on 2025-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_onesignal_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
